test_that("rescue aborts when boosters.toml is absent", {
  root <- withr::local_tempdir()

  expect_error(
    boosterpak:::.rescue(root = root, verbose = FALSE),
    "repairs existing boosterpak projects"
  )
})

test_that("rescue dry run reports planned repairs without file changes", {
  withr::local_options(list(
    repos = c(CRAN = "@CRAN@"),
    renv.config.repos.override = NULL,
    boosterpak.configure_repositories = TRUE
  ))
  withr::local_envvar(RENV_CONFIG_REPOS_OVERRIDE = NA)
  root <- withr::local_tempdir()
  boosterpak:::write_default_config(root)
  before <- list.files(root, all.files = TRUE, recursive = TRUE, no.. = TRUE)

  report <- boosterpak:::.rescue(root = root, dry_run = TRUE, verbose = FALSE)

  expect_true(report$dry_run)
  expect_true(any(grepl("would configure", report$actions)))
  expect_true(any(grepl("would repair \\.Rprofile", report$actions)))
  expect_true(any(grepl("would materialize built-in pack 'core'", report$actions, fixed = TRUE)))
  expect_true(any(grepl("would rewrite managed boosters/attach\\.R", report$actions)))
  expect_equal(
    list.files(root, all.files = TRUE, recursive = TRUE, no.. = TRUE),
    before
  )
  expect_false(file.exists(file.path(root, ".Rprofile")))
  expect_false(file.exists(file.path(root, "boosters", "packs", "core.toml")))
  expect_false(file.exists(file.path(root, "boosters", "attach.R")))
  expect_equal(getOption("repos")[["CRAN"]], "@CRAN@")
  expect_null(getOption("renv.config.repos.override"))
})

test_that("rescue repairs legacy Rprofile hook around renv activation", {
  withr::local_options(list(
    repos = c(CRAN = "@CRAN@"),
    renv.config.repos.override = NULL,
    boosterpak.configure_repositories = TRUE
  ))
  withr::local_envvar(RENV_CONFIG_REPOS_OVERRIDE = NA)
  root <- withr::local_tempdir()
  boosterpak:::write_default_config(root)
  writeLines(
    c(
      "before <- TRUE",
      boosterpak:::legacy_rprofile_line(),
      "source(\"renv/activate.R\")",
      "after <- TRUE"
    ),
    file.path(root, ".Rprofile")
  )

  boosterpak:::.rescue(root = root, verbose = FALSE)

  lines <- readLines(file.path(root, ".Rprofile"), warn = FALSE)
  marker <- match(boosterpak:::rprofile_repository_marker(), lines)
  renv_line <- grep('source\\("renv/activate\\.R"\\)', lines)
  hook_line <- match(boosterpak:::rprofile_line(), lines)

  expect_false(boosterpak:::legacy_rprofile_line() %in% lines)
  expect_true(marker < renv_line)
  expect_equal(hook_line, renv_line + 1L)
  expect_true("before <- TRUE" %in% lines)
  expect_true("after <- TRUE" %in% lines)
})

test_that("rescue snapshots workflow packages with update true", {
  withr::local_options(boosterpak.configure_repositories = FALSE)
  root <- withr::local_tempdir()
  boosterpak:::write_default_config(root)
  calls <- character()
  snapshotted <- NULL
  snapshot_update <- NULL

  local_mocked_bindings(
    has_project_renv = function(root = ".") TRUE,
    is_project_renv_active = function(root = ".") FALSE,
    call_renv_load = function(root = ".") {
      calls <<- c(calls, "load")
    },
    missing_packages = function(packages, root = ".") character(),
    call_renv_snapshot = function(root = ".", packages = NULL, update = FALSE) {
      snapshotted <<- packages
      snapshot_update <<- update
    },
    .package = "boosterpak"
  )

  boosterpak:::.rescue(root = root, verbose = FALSE)

  expect_equal(calls, "load")
  expect_equal(snapshotted, c("renv", "pak", "boosterpak"))
  expect_true(snapshot_update)
})

test_that("rescue materializes core pack and rewrites managed attach file", {
  withr::local_options(boosterpak.configure_repositories = FALSE)
  root <- withr::local_tempdir()
  boosterpak:::write_default_config(root)
  dir.create(file.path(root, "boosters"), recursive = TRUE, showWarnings = FALSE)
  writeLines("stale attach", file.path(root, "boosters", "attach.R"))

  boosterpak:::.rescue(root = root, verbose = FALSE)

  expect_true(file.exists(file.path(root, "boosters", "packs", "core.toml")))
  attach <- readLines(file.path(root, "boosters", "attach.R"), warn = FALSE)
  expect_equal(attach[[1]], "# Generated by boosterpak::write_attach(); do not edit by hand.")
  expect_false("stale attach" %in% attach)
})

test_that("rescue skips workflow repair when project renv is absent", {
  withr::local_options(boosterpak.configure_repositories = FALSE)
  root <- withr::local_tempdir()
  boosterpak:::write_default_config(root)

  report <- boosterpak:::.rescue(root = root, verbose = FALSE)

  expect_true(any(grepl("no project renv found", report$skipped)))
})

test_that("README documents bootstrap before hidden rescue when boosterpak is absent", {
  readme_path <- file.path(testthat::test_path(), "..", "..", "README.md")
  skip_if_not(
    file.exists(readme_path),
    "README.md is not available in installed package checks."
  )
  readme <- readLines(readme_path, warn = FALSE)

  expect_true(any(grepl('requireNamespace\\("renv"', readme)))
  expect_true(any(grepl("renv::load()", readme, fixed = TRUE)))
  expect_true(any(grepl('renv::install("pak"', readme, fixed = TRUE)))
  expect_true(any(grepl('pak::pkg_install("seanthimons/boosterpak"', readme, fixed = TRUE)))
  expect_true(any(grepl("boosterpak:::.rescue()", readme, fixed = TRUE)))
})
