test_that("deinit removes all supported project artifacts and nothing else", {
  root <- withr::local_tempdir()
  dir.create(file.path(root, "boosters", "packs"), recursive = TRUE)
  dir.create(file.path(root, "renv", "library"), recursive = TRUE)
  writeLines("[packs]", file.path(root, "boosters.toml"))
  writeLines("helper <- TRUE", file.path(root, "boosters", "fn_helper.R"))
  writeLines("activate", file.path(root, "renv", "activate.R"))
  writeLines("{}", file.path(root, "renv.lock"))
  writeLines(
    c("# air formatter configuration", ""),
    file.path(root, "air.toml")
  )
  writeLines("keep", file.path(root, "analysis.R"))

  call <- withVisible(deinit(root = root, force = TRUE, verbose = FALSE))

  expect_false(call$visible)
  expect_equal(call$value$root, normalizePath(root, winslash = "/"))
  expect_equal(
    call$value$selected,
    c("boosters", "renv", "lockfile", "air")
  )
  expect_equal(
    call$value$removed,
    c("boosters.toml", "boosters/", "renv/", "renv.lock", "air.toml")
  )
  expect_false(call$value$rprofile_changed)
  expect_equal(call$value$preserved, character())
  expect_false(call$value$restart_required)
  expect_false(call$value$cancelled)
  expect_false(file.exists(file.path(root, "boosters.toml")))
  expect_false(dir.exists(file.path(root, "boosters")))
  expect_false(dir.exists(file.path(root, "renv")))
  expect_false(file.exists(file.path(root, "renv.lock")))
  expect_false(file.exists(file.path(root, "air.toml")))
  expect_false(file.exists(file.path(root, ".Rprofile")))
  expect_equal(readLines(file.path(root, "analysis.R")), "keep")
})

test_that("deinit removes managed profile lines and preserves user code", {
  root <- withr::local_tempdir()
  path <- file.path(root, ".Rprofile")
  user_lines <- c(
    "before <- TRUE",
    "middle <- TRUE",
    '# source("renv/activate.R")',
    'if (interactive()) source("renv/activate.R")',
    'source(file.path("renv", "activate.R"))',
    "after <- TRUE"
  )
  writeLines(
    c(
      user_lines[[1]],
      boosterpak:::rprofile_startup_block(),
      boosterpak:::rprofile_startup_block(),
      user_lines[[2]],
      boosterpak:::rprofile_line(),
      boosterpak:::legacy_rprofile_line(),
      boosterpak:::rprofile_install_policy_lines(),
      boosterpak:::rprofile_repository_lines(
        c(CRAN = "https://packagemanager.posit.co/cran/latest")
      ),
      ' source("renv/activate.R") # generated by renv',
      "source('renv/activate.R')",
      user_lines[3:6]
    ),
    path
  )

  result <- deinit(
    root = root,
    boosters = FALSE,
    renv = TRUE,
    rprofile = TRUE,
    lockfile = FALSE,
    air = FALSE,
    force = TRUE,
    verbose = FALSE
  )

  expect_true(file.exists(path))
  expect_equal(readLines(path, warn = FALSE), user_lines)
  expect_equal(result$selected, "rprofile")
  expect_equal(result$removed, character())
  expect_true(result$rprofile_changed)
})

test_that("deinit retains an empty Rprofile and never deletes the file", {
  root <- withr::local_tempdir()
  path <- file.path(root, ".Rprofile")
  writeLines(boosterpak:::rprofile_startup_block(), path)

  result <- deinit(
    root,
    renv = FALSE,
    boosters = FALSE,
    rprofile = TRUE,
    lockfile = FALSE,
    air = FALSE,
    force = TRUE,
    verbose = FALSE
  )

  expect_true(file.exists(path))
  expect_equal(readLines(path, warn = FALSE), character())
  expect_true(result$rprofile_changed)
})

test_that("deinit selectors act independently", {
  parent <- withr::local_tempdir()
  project_number <- 0L
  make_project <- function() {
    project_number <<- project_number + 1L
    root <- file.path(parent, paste0("project-", project_number))
    dir.create(root)
    dir.create(file.path(root, "boosters"))
    dir.create(file.path(root, "renv"))
    writeLines("config", file.path(root, "boosters.toml"))
    writeLines("helper", file.path(root, "boosters", "fn_helper.R"))
    writeLines("activate", file.path(root, "renv", "activate.R"))
    writeLines("lock", file.path(root, "renv.lock"))
    writeLines(
      c("# air formatter configuration", ""),
      file.path(root, "air.toml")
    )
    writeLines(
      c(
        boosterpak:::rprofile_startup_block(),
        'source("renv/activate.R")'
      ),
      file.path(root, ".Rprofile")
    )
    root
  }

  root <- make_project()
  result <- deinit(
    root,
    renv = FALSE,
    boosters = TRUE,
    rprofile = FALSE,
    lockfile = FALSE,
    air = FALSE,
    force = TRUE,
    verbose = FALSE
  )
  expect_equal(result$selected, "boosters")
  expect_false(file.exists(file.path(root, "boosters.toml")))
  expect_false(dir.exists(file.path(root, "boosters")))
  expect_true(dir.exists(file.path(root, "renv")))

  root <- make_project()
  result <- deinit(
    root,
    renv = TRUE,
    boosters = FALSE,
    rprofile = FALSE,
    lockfile = FALSE,
    air = FALSE,
    force = TRUE,
    verbose = FALSE
  )
  expect_equal(result$selected, "renv")
  expect_false(dir.exists(file.path(root, "renv")))
  expect_equal(
    readLines(file.path(root, ".Rprofile"), warn = FALSE),
    c(boosterpak:::rprofile_startup_block(), 'source("renv/activate.R")')
  )
  expect_equal(
    unname(result$preserved[[".Rprofile"]]),
    "renv activation preserved by request"
  )

  root <- make_project()
  result <- deinit(
    root,
    renv = FALSE,
    boosters = FALSE,
    rprofile = TRUE,
    lockfile = FALSE,
    air = FALSE,
    force = TRUE,
    verbose = FALSE
  )
  expect_equal(result$selected, "rprofile")
  expect_equal(
    readLines(file.path(root, ".Rprofile"), warn = FALSE),
    'source("renv/activate.R")'
  )

  root <- make_project()
  result <- deinit(
    root,
    renv = FALSE,
    boosters = FALSE,
    rprofile = FALSE,
    lockfile = TRUE,
    air = FALSE,
    force = TRUE,
    verbose = FALSE
  )
  expect_equal(result$selected, "lockfile")
  expect_false(file.exists(file.path(root, "renv.lock")))
  expect_true(dir.exists(file.path(root, "renv")))

  root <- make_project()
  result <- deinit(
    root,
    renv = FALSE,
    boosters = FALSE,
    rprofile = FALSE,
    lockfile = FALSE,
    air = TRUE,
    force = TRUE,
    verbose = FALSE
  )
  expect_equal(result$selected, "air")
  expect_false(file.exists(file.path(root, "air.toml")))
  expect_true(file.exists(file.path(root, "boosters.toml")))
})

test_that("deinit validates roots, selectors, force, and verbose", {
  root <- withr::local_tempdir()
  for (name in c("renv", "boosters", "rprofile", "lockfile", "air", "force")) {
    for (value in list(NA, c(TRUE, FALSE), 1, NULL)) {
      args <- list(root = root, force = TRUE, verbose = FALSE)
      args[name] <- list(value)
      expect_error(do.call(deinit, args), name, fixed = TRUE)
    }
  }
  expect_error(
    deinit(root, force = TRUE, verbose = NA),
    "verbose",
    fixed = TRUE
  )
  expect_error(
    deinit(file.path(root, "missing"), force = TRUE, verbose = FALSE),
    "existing directory",
    fixed = TRUE
  )
})

test_that("default interactive deinit selects actionable components once", {
  root <- withr::local_tempdir()
  dir.create(file.path(root, "boosters"))
  writeLines("config", file.path(root, "boosters.toml"))
  writeLines("lock", file.path(root, "renv.lock"))
  writeLines(
    c(boosterpak:::rprofile_startup_block(), "user <- TRUE"),
    file.path(root, ".Rprofile")
  )
  offered <- NULL
  confirmed <- NULL
  local_mocked_bindings(
    .deinit_is_interactive = function() TRUE,
    .deinit_select_components = function(components) {
      offered <<- components
      c("boosters", "rprofile")
    },
    .deinit_confirm = function(plan) {
      confirmed <<- plan
      TRUE
    },
    .package = "boosterpak"
  )

  result <- deinit(root = root, verbose = FALSE)

  expect_equal(offered, c("boosters", "rprofile", "lockfile"))
  expect_equal(confirmed$selected, c("boosters", "rprofile"))
  normalized_root <- normalizePath(root, winslash = "/")
  expect_equal(
    confirmed$deletions$path,
    file.path(normalized_root, c("boosters.toml", "boosters"))
  )
  expect_equal(
    confirmed$rprofile$path,
    file.path(normalized_root, ".Rprofile")
  )
  expect_true(confirmed$rprofile$changed)
  expect_equal(result$selected, c("boosters", "rprofile"))
  expect_true(file.exists(file.path(root, "renv.lock")))
  expect_equal(readLines(file.path(root, ".Rprofile")), "user <- TRUE")
})

test_that("explicit selectors skip the picker and use final confirmation", {
  root <- withr::local_tempdir()
  writeLines("config", file.path(root, "boosters.toml"))
  confirmations <- 0L
  local_mocked_bindings(
    .deinit_is_interactive = function() TRUE,
    .deinit_select_components = function(components) {
      stop("picker should not be called")
    },
    .deinit_confirm = function(plan) {
      confirmations <<- confirmations + 1L
      TRUE
    },
    .package = "boosterpak"
  )

  result <- deinit(root = root, boosters = TRUE, verbose = FALSE)

  expect_equal(confirmations, 1L)
  expect_equal(result$selected, "boosters")
  expect_false(file.exists(file.path(root, "boosters.toml")))
})

test_that("interactive deselection excludes profile changes from the plan", {
  root <- withr::local_tempdir()
  writeLines("config", file.path(root, "boosters.toml"))
  writeLines(
    boosterpak:::rprofile_startup_block(),
    file.path(root, ".Rprofile")
  )
  confirmed <- NULL
  local_mocked_bindings(
    .deinit_is_interactive = function() TRUE,
    .deinit_select_components = function(components) "boosters",
    .deinit_confirm = function(plan) {
      confirmed <<- plan
      TRUE
    },
    .package = "boosterpak"
  )

  result <- deinit(root = root, verbose = FALSE)

  expect_false(confirmed$rprofile$changed)
  expect_equal(result$selected, "boosters")
  expect_equal(
    readLines(file.path(root, ".Rprofile"), warn = FALSE),
    boosterpak:::rprofile_startup_block()
  )
})

test_that("interactive cancellation never mutates the project", {
  root <- withr::local_tempdir()
  writeLines("config", file.path(root, "boosters.toml"))
  selection <- character()
  confirmation <- FALSE
  confirmations <- 0L
  local_mocked_bindings(
    .deinit_is_interactive = function() TRUE,
    .deinit_select_components = function(components) selection,
    .deinit_confirm = function(plan) {
      confirmations <<- confirmations + 1L
      confirmation
    },
    .package = "boosterpak"
  )

  result <- deinit(root = root, verbose = FALSE)

  expect_true(result$cancelled)
  expect_equal(result$selected, character())
  expect_equal(confirmations, 0L)
  expect_true(file.exists(file.path(root, "boosters.toml")))

  selection <- "boosters"
  result <- deinit(root = root, verbose = FALSE)
  expect_true(result$cancelled)
  expect_equal(result$selected, "boosters")
  expect_equal(confirmations, 1L)
  expect_true(file.exists(file.path(root, "boosters.toml")))
})

test_that("non-interactive cleanup requires force and force bypasses prompts", {
  root <- withr::local_tempdir()
  writeLines("config", file.path(root, "boosters.toml"))
  local_mocked_bindings(
    .deinit_is_interactive = function() FALSE,
    .deinit_select_components = function(components) stop("unexpected picker"),
    .deinit_confirm = function(plan) stop("unexpected confirmation"),
    .package = "boosterpak"
  )

  expect_error(
    deinit(root = root, boosters = TRUE, verbose = FALSE),
    "force = TRUE",
    fixed = TRUE
  )
  expect_true(file.exists(file.path(root, "boosters.toml")))

  result <- deinit(
    root = root,
    boosters = TRUE,
    force = TRUE,
    verbose = FALSE
  )
  expect_false(result$cancelled)
  expect_false(file.exists(file.path(root, "boosters.toml")))
})

test_that("a second deinit call is an unprompted no-op", {
  root <- withr::local_tempdir()
  writeLines("config", file.path(root, "boosters.toml"))
  deinit(root = root, force = TRUE, verbose = FALSE)
  local_mocked_bindings(
    .deinit_is_interactive = function() {
      stop("no-op should not inspect interactivity")
    },
    .deinit_select_components = function(components) stop("unexpected picker"),
    .deinit_confirm = function(plan) stop("unexpected confirmation"),
    .package = "boosterpak"
  )

  result <- deinit(root = root, verbose = FALSE)

  expect_equal(result$selected, character())
  expect_equal(result$removed, character())
  expect_false(result$cancelled)
})

test_that("deinit removes every unchanged generated Air format", {
  canonical <- c(
    "[format]",
    "line-width = 120",
    "indent-width = 2",
    'indent-style = "space"',
    'line-ending = "auto"',
    "persistent-line-breaks = true",
    "exclude = []",
    "default-exclude = true",
    "skip = []",
    "table = []",
    "default-table = true",
    ""
  )
  marker <- "# Generated by boosterpak; deinit() removes this file only while unchanged."
  formats <- list(
    marked = c(marker, canonical),
    unmarked = canonical,
    historical = c("# air formatter configuration", "")
  )

  parent <- withr::local_tempdir()
  for (name in names(formats)) {
    root <- file.path(parent, name)
    dir.create(root)
    writeLines(formats[[name]], file.path(root, "air.toml"))

    result <- deinit(
      root,
      renv = FALSE,
      boosters = FALSE,
      rprofile = FALSE,
      lockfile = FALSE,
      air = TRUE,
      force = TRUE,
      verbose = FALSE
    )

    expect_equal(result$selected, "air", info = name)
    expect_equal(result$removed, "air.toml", info = name)
    expect_false(file.exists(file.path(root, "air.toml")), info = name)
  }
})

test_that("deinit preserves edited and ownership-unknown Air files", {
  canonical <- c(
    "# Generated by boosterpak; deinit() removes this file only while unchanged.",
    "[format]",
    "line-width = 120",
    "indent-width = 2",
    'indent-style = "space"',
    'line-ending = "auto"',
    "persistent-line-breaks = true",
    "exclude = []",
    "default-exclude = true",
    "skip = []",
    "table = []",
    "default-table = true",
    ""
  )
  formats <- list(
    edited_marked = c(canonical, "# local edit"),
    malformed_marked = canonical[-3],
    unrecognized = c("[format]", "line-width = 80", "")
  )

  parent <- withr::local_tempdir()
  for (name in names(formats)) {
    root <- file.path(parent, name)
    dir.create(root)
    path <- file.path(root, "air.toml")
    writeLines(formats[[name]], path)

    result <- deinit(
      root,
      renv = FALSE,
      boosters = FALSE,
      rprofile = FALSE,
      lockfile = FALSE,
      air = TRUE,
      force = TRUE,
      verbose = FALSE
    )

    expect_true(file.exists(path), info = name)
    expect_equal(readLines(path, warn = FALSE), formats[[name]], info = name)
    expect_equal(result$selected, character(), info = name)
    expect_equal(
      unname(result$preserved[["air.toml"]]),
      "modified or ownership unknown",
      info = name
    )
  }
})

test_that("deinit warns and preserves malformed startup markers", {
  root <- withr::local_tempdir()
  path <- file.path(root, ".Rprofile")
  lines <- c(
    "user <- TRUE",
    boosterpak:::rprofile_startup_end_marker(),
    paste0(" ", boosterpak:::rprofile_line()),
    boosterpak:::rprofile_line(),
    boosterpak:::rprofile_startup_begin_marker(),
    "custom <- TRUE"
  )
  writeLines(lines, path)

  expect_warning(
    result <- deinit(
      root,
      renv = FALSE,
      boosters = FALSE,
      rprofile = TRUE,
      lockfile = FALSE,
      air = FALSE,
      force = TRUE,
      verbose = FALSE
    ),
    "malformed or unmatched"
  )

  expect_equal(result$selected, "rprofile")
  expect_equal(
    readLines(path, warn = FALSE),
    lines[lines != boosterpak:::rprofile_line()]
  )
  expect_true(
    paste0(" ", boosterpak:::rprofile_line()) %in%
      readLines(path, warn = FALSE)
  )
})

test_that("deinit never removes user pack configuration", {
  config_dir <- withr::local_tempdir()
  withr::local_envvar(R_USER_CONFIG_DIR = config_dir)
  user_dir <- boosterpak:::user_packs_dir()
  dir.create(user_dir, recursive = TRUE)
  sentinel <- file.path(user_dir, "sentinel.toml")
  writeLines("keep", sentinel)

  project <- withr::local_tempdir()
  dir.create(file.path(project, "boosters"))
  writeLines("config", file.path(project, "boosters.toml"))
  deinit(project, force = TRUE, verbose = FALSE)

  expect_equal(readLines(sentinel), "keep")
})

test_that("deinit aborts before mutation when a target overlaps user packs", {
  config_dir <- withr::local_tempdir()
  withr::local_envvar(R_USER_CONFIG_DIR = config_dir)
  root <- file.path(config_dir, "R")
  user_dir <- boosterpak:::user_packs_dir()
  dir.create(user_dir, recursive = TRUE)
  sentinel <- file.path(user_dir, "sentinel.toml")
  writeLines("keep", sentinel)
  writeLines("config", file.path(root, "boosters.toml"))

  expect_error(
    deinit(
      root,
      renv = FALSE,
      boosters = TRUE,
      rprofile = FALSE,
      lockfile = FALSE,
      air = FALSE,
      force = TRUE,
      verbose = FALSE
    ),
    "overlaps user pack configuration"
  )

  expect_true(file.exists(file.path(root, "boosters.toml")))
  expect_equal(readLines(sentinel), "keep")
})

test_that("deinit verifies deletion and reports partial failure truthfully", {
  root <- withr::local_tempdir()
  dir.create(file.path(root, "boosters"))
  writeLines("config", file.path(root, "boosters.toml"))
  writeLines(
    c(boosterpak:::rprofile_startup_block(), "user <- TRUE"),
    file.path(root, ".Rprofile")
  )
  local_mocked_bindings(
    .deinit_unlink = function(path) {
      if (identical(basename(path), "boosters")) {
        return(invisible(1L))
      }
      unlink(path, recursive = TRUE, force = TRUE, expand = FALSE)
    },
    .package = "boosterpak"
  )

  expect_error(
    deinit(
      root,
      renv = FALSE,
      boosters = TRUE,
      rprofile = TRUE,
      lockfile = FALSE,
      air = FALSE,
      force = TRUE,
      verbose = FALSE
    ),
    regexp = "(?s)boosters/.*Successfully removed: boosters.toml",
    perl = TRUE
  )

  expect_false(file.exists(file.path(root, "boosters.toml")))
  expect_true(dir.exists(file.path(root, "boosters")))
  expect_equal(readLines(file.path(root, ".Rprofile")), "user <- TRUE")
})

test_that("deinit reports active renv cleanup and requires restart", {
  root <- withr::local_tempdir()
  dir.create(file.path(root, "renv"))
  writeLines("activate", file.path(root, "renv", "activate.R"))
  local_mocked_bindings(
    is_project_renv_active = function(root = ".") TRUE,
    .package = "boosterpak"
  )

  expect_message(
    result <- deinit(
      root,
      renv = TRUE,
      boosters = FALSE,
      rprofile = FALSE,
      lockfile = FALSE,
      air = FALSE,
      force = TRUE,
      verbose = FALSE
    ),
    "restart R"
  )

  expect_true(result$restart_required)
  expect_false(dir.exists(file.path(root, "renv")))
})
