test_that("default attach resolves pack packages but excludes workflow packages", {
  root <- withr::local_tempdir()
  init(root = root, renv = "no", rprofile = "no", verbose = FALSE)
  add_pack("example", root = root, sync = FALSE, verbose = FALSE)
  config <- boosterpak:::read_config(root)

  expect_equal(boosterpak:::resolve_config_attach_packages(config, root), "cli")
})

test_that("pack attach true and false resolve explicitly", {
  root <- withr::local_tempdir()
  init(root = root, renv = "no", rprofile = "no", verbose = FALSE)
  writeLines(c(
    'name = "yesattach"',
    'description = "Attach direct package."',
    'packages = ["cli"]',
    "attach = true"
  ), file.path(root, "boosters", "packs", "yesattach.toml"))
  writeLines(c(
    'name = "noattach"',
    'description = "Install without attach."',
    'packages = ["glue"]',
    "attach = false"
  ), file.path(root, "boosters", "packs", "noattach.toml"))
  boosterpak:::update_declared_array(file.path(root, "boosters.toml"), "packs", "declared", c("yesattach", "noattach"))

  expect_equal(boosterpak:::resolve_config_attach_packages(boosterpak:::read_config(root), root), "cli")
})

test_that("attach declared can explicitly add workflow packages", {
  root <- withr::local_tempdir()
  init(root = root, renv = "no", rprofile = "no", verbose = FALSE)
  path <- file.path(root, "boosters.toml")
  lines <- readLines(path, warn = FALSE)
  attach_section <- grep("^\\[attach\\]$", lines)
  lines[attach_section + grep("^declared =", lines[(attach_section + 1):length(lines)])[1]] <- 'declared = ["boosterpak"]'
  writeLines(lines, path)
  config <- boosterpak:::read_config(root)

  expect_true("boosterpak" %in% boosterpak:::resolve_config_attach_packages(config, root))
})

test_that("attach exclude and install exclude remove startup packages", {
  root <- withr::local_tempdir()
  init(root = root, renv = "no", rprofile = "no", verbose = FALSE)
  add_pack("example", root = root, sync = FALSE, verbose = FALSE)
  path <- file.path(root, "boosters.toml")
  lines <- readLines(path, warn = FALSE)
  attach_section <- grep("^\\[attach\\]$", lines)
  lines[attach_section + grep("^exclude =", lines[(attach_section + 1):length(lines)])[1]] <- 'exclude = ["cli"]'
  writeLines(lines, path)

  expect_equal(boosterpak:::resolve_config_attach_packages(boosterpak:::read_config(root), root), character())

  lines <- readLines(path, warn = FALSE)
  lines[lines == 'exclude = ["cli"]'] <- "exclude = []"
  exclude_section <- grep("^\\[exclude\\]$", lines)
  lines[exclude_section + grep("^declared =", lines[(exclude_section + 1):length(lines)])[1]] <- 'declared = ["cli"]'
  writeLines(lines, path)

  expect_equal(boosterpak:::resolve_config_attach_packages(boosterpak:::read_config(root), root), character())
})

test_that("pack attach vector writes deterministic library calls", {
  root <- withr::local_tempdir()
  init(root = root, renv = "no", rprofile = "no", verbose = FALSE)
  writeLines(c(
    'name = "selected"',
    'description = "Attach selected package."',
    'packages = ["cli", "glue"]',
    'attach = ["glue"]'
  ), file.path(root, "boosters", "packs", "selected.toml"))
  boosterpak:::update_declared_array(file.path(root, "boosters.toml"), "packs", "declared", "selected")

  path <- write_attach(root, verbose = FALSE)
  lines <- readLines(path, warn = FALSE)

  expect_equal(lines[1], "# Generated by boosterpak::write_attach(); do not edit by hand.")
  expect_equal(grep("^library", lines, value = TRUE), "library(glue)")
})

test_that("disabled attach removes managed attach file", {
  root <- withr::local_tempdir()
  init(root = root, renv = "no", rprofile = "no", verbose = FALSE)
  write_attach(root, verbose = FALSE)
  path <- boosterpak:::attach_file(root)
  expect_true(file.exists(path))

  lines <- readLines(file.path(root, "boosters.toml"), warn = FALSE)
  lines[lines == "enabled = true"] <- "enabled = false"
  writeLines(lines, file.path(root, "boosters.toml"))

  write_attach(root, verbose = FALSE)
  expect_false(file.exists(path))
})

test_that("sync writes attach file before snapshot", {
  root <- withr::local_tempdir()
  init(root = root, renv = "no", rprofile = "no", verbose = FALSE)
  add_pack("example", root = root, sync = FALSE, verbose = FALSE)
  snapshotted_after_attach <- NULL

  local_mocked_bindings(
    ensure_project_renv = function(root = ".") TRUE,
    missing_packages = function(packages, root = ".") character(),
    install_via = function(specs, root = ".") TRUE,
    call_renv_snapshot = function(root = ".", packages = NULL) {
      snapshotted_after_attach <<- file.exists(boosterpak:::attach_file(root))
    },
    .package = "boosterpak"
  )

  sync(root = root, verbose = FALSE)

  expect_true(snapshotted_after_attach)
  expect_equal(grep("^library", readLines(boosterpak:::attach_file(root), warn = FALSE), value = TRUE), "library(cli)")
})

test_that("sync removes managed attach file when attach is disabled", {
  root <- withr::local_tempdir()
  init(root = root, renv = "no", rprofile = "no", verbose = FALSE)
  write_attach(root, verbose = FALSE)
  lines <- readLines(file.path(root, "boosters.toml"), warn = FALSE)
  lines[lines == "enabled = true"] <- "enabled = false"
  writeLines(lines, file.path(root, "boosters.toml"))

  local_mocked_bindings(
    ensure_project_renv = function(root = ".") TRUE,
    missing_packages = function(packages, root = ".") character(),
    install_via = function(specs, root = ".") TRUE,
    call_renv_snapshot = function(root = ".", packages = NULL) TRUE,
    .package = "boosterpak"
  )

  sync(root = root, verbose = FALSE)

  expect_false(file.exists(boosterpak:::attach_file(root)))
})
